name: Get SHA256

on: [push]

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Print Keystore SHA-256
        run: keytool -list -v -keystore frontend/android/app/aloshipp-customer.jks -alias customer_alias -storepass 123456 -keypass 123456
